<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of ZfExtended library
 
 Copyright (c) 2013 - 2017 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU LESSER GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file lgpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU LESSER GENERAL PUBLIC LICENSE version 3.0 requirements will be met:
https://www.gnu.org/licenses/lgpl-3.0.txt

 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU LESSER GENERAL PUBLIC LICENSE version 3
			 https://www.gnu.org/licenses/lgpl-3.0.txt

END LICENSE AND COPYRIGHT
*/

/**#@+
 * @author Marc Mittag
 * @package ZfExtended
 * @version 2.0
 *
 */

$this->render('general.phtml');

$this->subject = $this->templateApply('{appName} - Ankündigung Server Wartung');

$mail = $this->templateApply('{header}
Aufgrund von Wartungsmaßnahmen wird {appName} auf {portalUrl}<br />
für kurze Zeit nicht erreichbar sein.<br />
<br />
Die Wartung ist geplant für: {maintenanceDate}.<br />
{additionalInfo}Die genaue Uhrzeit der Wartung wird in der Anwendung selbst angezeigt, <br />
mit einem zeitlichen Vorlauf von einer Stunde.<br />
<br />
Wir bitten um Ihr Verständnis.<br />
<br />
Sie erhalten diese automatisch versendete E-Mail,
da sie als Administrator eingetragen sind.<br />
{footer}', [
    'header' => $this->header,
    'footer' => $this->footer,
    'maintenanceDate' => $this->maintenanceDate,
    'additionalInfo' => empty($this->message) ? '' : $this->templateApply('Zusätzliche Informationen: {message}'."<br />\n<br />\n",['message' => $this->message]),
]);

$this->textbody = strip_tags($mail);

echo $mail;

