<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of ZfExtended library

 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU LESSER GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file lgpl3-license.txt
 included in the packaging of this file.  Please review the following information
 to ensure the GNU LESSER GENERAL PUBLIC LICENSE version 3.0 requirements will be met:
https://www.gnu.org/licenses/lgpl-3.0.txt

 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU LESSER GENERAL PUBLIC LICENSE version 3
             https://www.gnu.org/licenses/lgpl-3.0.txt

END LICENSE AND COPYRIGHT
*/

/** @var ZfExtended_View $this */

$this->render('general.phtml');

$this->subject = $this->templateApply('{appName} – server maintenance announcement');

$mail = $this->templateApply('{header}
Please note that {appName} on {portalUrl}<br />
will be temporarily unavailable due to scheduled maintenance.<br />
<br />
The maintenance is planned for:{maintenanceDate}.<br />
{additionalInfo}The exact time is displayed in the application,<br />
one hour in advance.<br />
<br />
We appreciate your understanding.<br />
<br />
You are receiving this automated e-mail,
as you are registered as an administrator.<br />
{footer}', [
    'header' => $this->header,
    'footer' => $this->footer,
    'maintenanceDate' => $this->maintenanceDate,
    'additionalInfo' => empty($this->message) ? '' : $this->templateApply(
        $this->translate->_('Additional information') . ": {message}<br />\n<br />\n",
        [
            'message' => $this->message,
        ]
    ),
]);

$this->textbody = strip_tags($mail);

echo $mail;
