<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of ZfExtended library

 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU LESSER GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file lgpl3-license.txt
 included in the packaging of this file.  Please review the following information
 to ensure the GNU LESSER GENERAL PUBLIC LICENSE version 3.0 requirements will be met:
https://www.gnu.org/licenses/lgpl-3.0.txt

 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU LESSER GENERAL PUBLIC LICENSE version 3
			 https://www.gnu.org/licenses/lgpl-3.0.txt

END LICENSE AND COPYRIGHT
*/

/**#@+
 * @author Leon Kyz
 * @package ZfExtended
 * @version 2.0
 *
 */

$this->render('general.phtml');

// Ask
$this->subject = $this->translate->_('Loginname geändert');

echo $this->templateApply('{header}
Wir haben festgestellt, dass Ihr Login-Name nicht unterstützte Zeichen enthält.
Der Login-Name wurde automatisch geändert.

Ihr neuer Login-Name:
------------------------------
{newLogin}
------------------------------

{footer}',[
    'header' => strip_tags($this->header), //since we send plain text here, we have to remove tags
    'footer' => strip_tags($this->footer),
    'newLogin' => $this->newLogin,
]);




