<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of ZfExtended library

 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU LESSER GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file lgpl3-license.txt
 included in the packaging of this file.  Please review the following information
 to ensure the GNU LESSER GENERAL PUBLIC LICENSE version 3.0 requirements will be met:
https://www.gnu.org/licenses/lgpl-3.0.txt

 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU LESSER GENERAL PUBLIC LICENSE version 3
             https://www.gnu.org/licenses/lgpl-3.0.txt

END LICENSE AND COPYRIGHT
*/

/**#@+
 * @author Marc Mittag
 * @package ZfExtended
 * @version 2.0
 *
 */

$this->render('general.phtml');

$this->subject = $this->translate->_('Reset password');

echo $this->templateApply('{header}
You have received this e-mail because we have received a request to change the password for your account at {portalUrl}.

If you have sent such a request and would like to change your password, please follow these instructions:

The following link contains a key which is valid for 30 minutes, and which can be used to reset your password. For security reasons, this will only work if you open the link in the same browser in which you requested the change to your password, and in addition, if you have not reopened your browser after resetting the password.

==============================
Link to reset password
------------------------------
{portalUrl}{hashurl}
------------------------------
==============================

If your key is no longer valid, you can request a new one at any time.
------------------------------
{portalUrl}{reseturl}
------------------------------

If you did not send the request yourself, please inform us of this.

{footer}', [
    'hashurl' => '/login/passwdnew?resetHash=' . $this->resetHash,
    'reseturl' => '/login/passwdreset',
    'header' => strip_tags($this->header), //since we send plain text here, we have to remove tags
    'footer' => strip_tags($this->footer),
]);
