<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of ZfExtended library
 
 Copyright (c) 2013 - 2015 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3.0 requirements will be met:
 http://www.gnu.org/licenses/agpl.html

 There is a plugin exception available for use with this release of translate5 for
 open source applications that are distributed under a license other than AGPL:
 Please see Open Source License Exception for Development of Plugins for translate5
 http://www.translate5.net/plugin-exception.txt or as plugin-exception.txt in the root
 folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execptions
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/**#@+
 * @author Marc Mittag
 * @package ZfExtended
 * @version 2.0
 *
 */

$session = new Zend_Session_Namespace();
echo sprintf($this->translate->_('%1$s %2$s,

Sie erhalten diese Email, weil wir eine Anfrage zur Änderung des Passwortes für Ihr Konto auf %3$s%4$s%5$s erhalten haben. 

Wenn Sie Ihr Passwort ändern möchten, dann befolgen Sie bitte folgende Anweisungen:

Der folgende Link enthält einen für 30 Minuten gültigen Schlüssel, mit welchem Sie Ihr Passwort neu setzen können. Aus Sicherheitsgründen funktioniert dies nur, wenn Sie den folgenden Link im selben Browser in dem Sie die Änderung Ihres Passwort angefordert haben öffnen und zudem nach Zurücksetzen des Passworts Ihren Browser nicht neu gestartet haben.

==============================
Link um Passwort neu zu setzen
------------------------------
%3$s%4$s%5$s%6$s
------------------------------
==============================

Sollte Ihr Schlüssel nicht mehr gültig sein, können Sie unter jederzeit einen neuen Schlüssel anfordern.
------------------------------
%3$s%4$s%5$s%7$s
------------------------------

Sollten Sie die Anfrage nicht selbst ausgelöst haben, bitten wir Sie uns darüber zu informieren.

Vielen Dank und viele Grüße,
Ihr Projektmanagement Team
%8$s

Diese Email wurde automatisch generiert. Please do not reply to this email.'),
    $this->mailEmployeeSalutation($this->gender),
    $this->surname,
    $session->runtimeOptions->server->protocol,
    $session->runtimeOptions->server->name,
    APPLICATION_RUNDIR,
    '/login/passwdnew?resetHash='.$this->resetHash,
    '/login/passwdreset',
    $session->runtimeOptions->companyName
);




