<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of ZfExtended library
 
 Copyright (c) 2013 - 2017 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU LESSER GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file lgpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU LESSER GENERAL PUBLIC LICENSE version 3.0 requirements will be met:
https://www.gnu.org/licenses/lgpl-3.0.txt

 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU LESSER GENERAL PUBLIC LICENSE version 3
			 https://www.gnu.org/licenses/lgpl-3.0.txt

END LICENSE AND COPYRIGHT
*/

/**#@+
 * @author Marc Mittag
 * @package ZfExtended
 * @version 2.0
 *
 */

$session = new Zend_Session_Namespace();
echo sprintf($this->translate->_('%1$s %2$s,

Sie erhalten diese Email, weil wir eine Anfrage zur Änderung des Passwortes für Ihr Konto auf %3$s%4$s%5$s erhalten haben. 

Wenn Sie Ihr Passwort ändern möchten, dann befolgen Sie bitte folgende Anweisungen:

Der folgende Link enthält einen für 30 Minuten gültigen Schlüssel, mit welchem Sie Ihr Passwort neu setzen können. Aus Sicherheitsgründen funktioniert dies nur, wenn Sie den folgenden Link im selben Browser in dem Sie die Änderung Ihres Passwort angefordert haben öffnen und zudem nach Zurücksetzen des Passworts Ihren Browser nicht neu gestartet haben.

==============================
Link um Passwort neu zu setzen
------------------------------
%3$s%4$s%5$s%6$s
------------------------------
==============================

Sollte Ihr Schlüssel nicht mehr gültig sein, können Sie unter jederzeit einen neuen Schlüssel anfordern.
------------------------------
%3$s%4$s%5$s%7$s
------------------------------

Sollten Sie die Anfrage nicht selbst ausgelöst haben, bitten wir Sie uns darüber zu informieren.

Vielen Dank und viele Grüße,
Ihr Projektmanagement Team
%8$s

Diese Email wurde automatisch generiert. Please do not reply to this email.'),
    $this->mailEmployeeSalutation($this->gender),
    $this->surname,
    $session->runtimeOptions->server->protocol,
    $session->runtimeOptions->server->name,
    APPLICATION_RUNDIR,
    '/login/passwdnew?resetHash='.$this->resetHash,
    '/login/passwdreset',
    $session->runtimeOptions->companyName
);




