<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of ZfExtended library
 
 Copyright (c) 2013 - 2017 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU LESSER GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file lgpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU LESSER GENERAL PUBLIC LICENSE version 3.0 requirements will be met:
https://www.gnu.org/licenses/lgpl-3.0.txt

 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU LESSER GENERAL PUBLIC LICENSE version 3
			 https://www.gnu.org/licenses/lgpl-3.0.txt

END LICENSE AND COPYRIGHT
*/

/**#@+
 * @author Marc Mittag
 * @package ZfExtended
 * @version 2.0
 *
 */

$session = new Zend_Session_Namespace();
$userLocale=null;
if($this->userEntity->getLocale() && $this->userEntity->getLocale()!==''){
    $userLocale=$this->userEntity->getLocale();
}
echo sprintf($this->translate->_('%1$s %2$s,

Sie erhalten diese Email, weil Ihr Konto auf %3$s neu angelegt oder Ihr Passwort zurückgesetzt wurde. 

Ihr Benutzername:
------------------------------
%6$s
------------------------------

Wenn Sie Ihr Konto künftig nutzen möchten, dann fordern Sie unter der folgenden
Adresse eine Link an, um Ihr Passwort neu setzen zu können.

------------------------------
%3$s%4$s
------------------------------

Vielen Dank und viele Grüße,
Ihr Projektmanagement Team
%5$s

Diese Email wurde automatisch generiert. Bitte antworten Sie nicht auf diese E-Mail.',
        $userLocale),
        $this->mailEmployeeSalutation($this->userEntity->getGender(),$userLocale),
    $this->userEntity->getSurName(),
    $session->runtimeOptions->server->protocol.$session->runtimeOptions->server->name.APPLICATION_RUNDIR,//site-url
    '/login/passwdreset',
    $session->runtimeOptions->companyName,
    $this->userEntity->getLogin()
);




