<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of ZfExtended library
 
 Copyright (c) 2013 - 2015 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3.0 requirements will be met:
 http://www.gnu.org/licenses/agpl.html

 There is a plugin exception available for use with this release of translate5 for
 open source applications that are distributed under a license other than AGPL:
 Please see Open Source License Exception for Development of Plugins for translate5
 http://www.translate5.net/plugin-exception.txt or as plugin-exception.txt in the root
 folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execptions
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/**#@+
 * @author Marc Mittag
 * @package ZfExtended
 * @version 2.0
 *
 */

$session = new Zend_Session_Namespace();
echo sprintf($this->translate->_('%1$s %2$s,

Sie erhalten diese Email, weil Ihr Konto auf %3$s neu angelegt oder Ihr Passwort zurückgesetzt wurde. 

Ihr Benutzername:
------------------------------
%6$s
------------------------------

Wenn Sie Ihr Konto künftig nutzen möchten, dann fordern Sie unter der folgenden
Adresse eine Link an, um Ihr Passwort neu setzen zu können.

------------------------------
%3$s%4$s
------------------------------

Vielen Dank und viele Grüße,
Ihr Projektmanagement Team
%5$s

Diese Email wurde automatisch generiert. Bitte antworten Sie nicht auf diese E-Mail.'),
    $this->mailEmployeeSalutation($this->userEntity->getGender()),
    $this->userEntity->getSurName(),
    $session->runtimeOptions->server->protocol.$session->runtimeOptions->server->name.APPLICATION_RUNDIR,//site-url
    '/login/passwdreset',
    $session->runtimeOptions->companyName,
    $this->userEntity->getLogin()
);




