<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of ZfExtended library
 
 Copyright (c) 2013 - 2017 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU LESSER GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file lgpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU LESSER GENERAL PUBLIC LICENSE version 3.0 requirements will be met:
https://www.gnu.org/licenses/lgpl-3.0.txt

 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU LESSER GENERAL PUBLIC LICENSE version 3
			 https://www.gnu.org/licenses/lgpl-3.0.txt

END LICENSE AND COPYRIGHT
*/

/**#@+
 * @author Marc Mittag
 * @package ZfExtended
 * @version 2.0
 *
 */

$this->render('general.phtml');

$this->subject = $this->translate->_('Passwort setzen');

echo $this->templateApply('{header}
Sie erhalten diese Email, weil Ihr Konto auf {portalUrl} neu angelegt oder Ihr Passwort zurückgesetzt wurde. 

Ihr Benutzername:
------------------------------
{login}
------------------------------

Wenn Sie Ihr Konto künftig nutzen möchten, dann fordern Sie unter der folgenden
Adresse eine Link an, um Ihr Passwort neu setzen zu können.

------------------------------
{portalUrl}{reseturl}
------------------------------

{footer}',[
    'reseturl' => '/login/passwdreset',
    'header' => strip_tags($this->header), //since we send plain text here, we have to remove tags
    'footer' => strip_tags($this->footer),
    'login' => $this->receiver->login,
]);




