<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of ZfExtended library
 
 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU LESSER GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file lgpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU LESSER GENERAL PUBLIC LICENSE version 3.0 requirements will be met:
https://www.gnu.org/licenses/lgpl-3.0.txt

 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU LESSER GENERAL PUBLIC LICENSE version 3
			 https://www.gnu.org/licenses/lgpl-3.0.txt

END LICENSE AND COPYRIGHT
*/

/**#@+
 * @author Marc Mittag
 * @package ZfExtended
 * @version 2.0
 *
 */
?>
<article class="post">
    <header>
        <div class="title"><h2><?php echo $this->translate->_('Login'); ?></h2></div>
    </header>
    <?php
if(isset($this->message)): ?><p class="message"><?php echo $this->message;  ?></p><?php endif;
if(count($this->form->getErrorMessages())>0){ ?>
    <ul class="errors">
    <?php
    foreach ($this->form->getErrorMessages() as $message) {
        ?><li><?php echo $message; ?></li><?php
    }
    ?>
    </ul>
    <?php
}
echo $this->form->__toString(); ?>
<p><a href="<?php echo APPLICATION_RUNDIR; ?>/login/passwdreset"><?php echo $this->translate->_('Passwort neu setzen'); ?></a></p>
    </article>