<?php
 /*
   START LICENSE AND COPYRIGHT

  This file is part of the ZfExtended library and build on Zend Framework

  Copyright (c) 2013 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

  Contact:  http://www.MittagQI.com/  /  service (ÄTT) MittagQI.com

  This file is multi-licensed under the EPL, LGPL and GPL licenses. 

  It may be used under the terms of the Eclipse Public License - v 1.0
  as published by the Eclipse Foundation and appearing in the file eclipse-license.txt 
  included in the packaging of this file.  Please review the following information 
  to ensure the Eclipse Public License - v 1.0 requirements will be met:
  http://www.eclipse.org/legal/epl-v10.html.

  Also it may be used under the terms of the GNU LESSER GENERAL PUBLIC LICENSE version 3
  or the GNU GENERAL PUBLIC LICENSE version 3 as published by the 
  Free Software Foundation, Inc. and appearing in the files lgpl-license.txt and gpl3-license.txt
  included in the packaging of this file.  Please review the following information 
  to ensure the GNU LESSER GENERAL PUBLIC LICENSE version 3 requirements or the
  GNU GENERAL PUBLIC LICENSE version 3 requirements will be met:
  http://www.gnu.org/licenses/lgpl.html   /  http://www.gnu.org/licenses/gpl.html
  
  @copyright  Marc Mittag, MittagQI - Quality Informatics
  @author     MittagQI - Quality Informatics
  @license    Multi-licensed under Eclipse Public License - v 1.0 http://www.eclipse.org/legal/epl-v10.html, GNU LESSER GENERAL PUBLIC LICENSE version 3 http://www.gnu.org/licenses/lgpl.html and GNU GENERAL PUBLIC LICENSE version 3 http://www.gnu.org/licenses/gpl.html

  END LICENSE AND COPYRIGHT 
 */

/**#@+
 * @author Marc Mittag
 * @package ZfExtended
 * @version 2.0
 *
 */
$session = new Zend_Session_Namespace();
?><?php if(isset($this->message)): ?><h2><?php echo $this->message;  ?></h2><?php endif;
if($this->form->isErrors()){ ?>
    <h2 class="errors"><?php echo $this->translate->_('Fehler im Formular'); ?></h2>
    <ul class="errors">
    <?php
    foreach ($this->form->getErrorMessages() as $message) {
        ?><li><?php echo $message; ?></li><?php
    }
    ?>
    </ul>
    <?php
    if($this->passwdResetInfo){
        ?><p><?php echo $this->translate->_('Bitte setzen Sie Ihr Passwort ggf. nochmals zurück. Sie bekommen dann nochmals eine E-Mail mit einem neuen Reset-Hash zugesandt. Dieser ist wiederum für 30 min gültig, so lange Sie Ihren Browser geöffnet lassen.'); ?><br/><br/><a href="<?php echo APPLICATION_RUNDIR; ?>/login/passwdreset"><?php echo $this->translate->_('Passwort neu setzen'); ?></a></p><?php
    }
}
if(!$this->passwdResetInfo){
   echo $this->form;
}