<?php
 /*
   START LICENSE AND COPYRIGHT

  This file is part of the ZfExtended library and build on Zend Framework

  Copyright (c) 2013 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

  Contact:  http://www.MittagQI.com/  /  service (ÄTT) MittagQI.com

  This file is multi-licensed under the EPL, LGPL and GPL licenses. 

  It may be used under the terms of the Eclipse Public License - v 1.0
  as published by the Eclipse Foundation and appearing in the file eclipse-license.txt 
  included in the packaging of this file.  Please review the following information 
  to ensure the Eclipse Public License - v 1.0 requirements will be met:
  http://www.eclipse.org/legal/epl-v10.html.

  Also it may be used under the terms of the GNU LESSER GENERAL PUBLIC LICENSE version 3
  or the GNU GENERAL PUBLIC LICENSE version 3 as published by the 
  Free Software Foundation, Inc. and appearing in the files lgpl-license.txt and gpl3-license.txt
  included in the packaging of this file.  Please review the following information 
  to ensure the GNU LESSER GENERAL PUBLIC LICENSE version 3 requirements or the
  GNU GENERAL PUBLIC LICENSE version 3 requirements will be met:
  http://www.gnu.org/licenses/lgpl.html   /  http://www.gnu.org/licenses/gpl.html
  
  @copyright  Marc Mittag, MittagQI - Quality Informatics
  @author     MittagQI - Quality Informatics
  @license    Multi-licensed under Eclipse Public License - v 1.0 http://www.eclipse.org/legal/epl-v10.html, GNU LESSER GENERAL PUBLIC LICENSE version 3 http://www.gnu.org/licenses/lgpl.html and GNU GENERAL PUBLIC LICENSE version 3 http://www.gnu.org/licenses/gpl.html

  END LICENSE AND COPYRIGHT 
 */

if($this->importStarted) {
    echo '<h2>Choosen SQL Files were imported!</h2>';
    if(!empty($this->errors)) {
        echo '<b>With the following errors:</b><pre>';
        print_r($this->errors);
        echo '</pre>';
    }
}

if(empty($this->sqlFilesNew) && empty($this->sqlFilesChanged)) {
    echo "<h2>No modified / new SQL files found!</h2><br /><br />";
    return;
}

$printTable = function(array $data, $checkBoxCls) {
    $cellcss = ' style="border:1px solid black; padding:0 5px;"';
    echo '<table style="border:1px solid black;border-collapse: collapse;">';
    echo '<tr><th'.$cellcss.'>Origin SQL Package</th><th'.$cellcss.'>SQL File</th>';
    echo '<th><input type="checkbox" name="checkall" onclick="toggle(this,\''.$checkBoxCls.'\');"/></th></tr>';
    $row = '<tr><td%1$s>%2$s</td><td%1$s>%3$s</td><td%1$s><input class="%5$s" type="checkbox" name="%4$s" value="1"></td></tr>';
    foreach($data as $file) {
        printf($row, $cellcss, $file['origin'], $file['relativeToOrigin'], $file['entryHash'], $checkBoxCls);
    }
    echo '</table>';
};

echo '<form action="'.$_SERVER['REQUEST_URI'].'" method="post" name="toprocess">';
if(!empty($this->sqlFilesNew)) {
    echo '<h2>New SQL files found:</h2>';
    $printTable($this->sqlFilesNew, 'checkerNew');
}
if(!empty($this->sqlFilesChanged)) {
    echo '<h2>Modified SQL files found:</h2>';
    echo '<p style="font-style:italic;">This files has to been applied manually to the database:</p>';
    $printTable($this->sqlFilesChanged, 'checkerChanged');
}
?>
<br />
<br />
<br />
    <input type="hidden" name="startimport" value="true" />
    <button type="submit">Import New Files / Update Modified in DB</button>
    <br />
    <input type="checkbox" name="catchup" value="1" id="catchupbox"/>
    <label for="catchupbox">catchup mode - WARNING: the choosen files are assumed as already imported!</label>
</form><?php //start form above in PHP CODE! ?>
<script type="text/javascript">
function toggle(master) {
    boxes = document.getElementsByClassName('checker');
    for(var i=0; i<boxes.length;i++) {
        boxes[i].checked = master.checked;
    }
}
</script>