<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of ZfExtended library
 
 Copyright (c) 2013 - 2017 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU LESSER GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file lgpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU LESSER GENERAL PUBLIC LICENSE version 3.0 requirements will be met:
https://www.gnu.org/licenses/lgpl-3.0.txt

 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU LESSER GENERAL PUBLIC LICENSE version 3
			 https://www.gnu.org/licenses/lgpl-3.0.txt

END LICENSE AND COPYRIGHT
*/

/* * #@+
 * @author Marc Mittag
 * @package ZfExtended
 * @version 2.0
 *
 */

/*
 * Gibt Fehlerdetails nur für Fehler mit _errorCode größer 202 aus, da davon 
 * ausgegangen wird, dass alles andere nur Infomeldungen sind, bei denen nur die Message relevant ist
 */
?>
<?php
foreach ($this->errors as $error) {
    if(empty($error->_errorMessage)) {
        continue;
    }
    ?>
    <h2><?php echo $error->_errorMessage; ?></h2>
    <?php
    if($error->_errorCode > 202){
        ?>
        <h3>Stack trace:</h3>
        <pre><?php echo $error->_errorTrace; ?>
        </pre>
        <?php
    }
}
?>
<h3>Request Parameters:</h3>
<pre><?php echo var_export($this->getParams, true); ?>
</pre><?php 