<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of ZfExtended library
 
 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU LESSER GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file lgpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU LESSER GENERAL PUBLIC LICENSE version 3.0 requirements will be met:
https://www.gnu.org/licenses/lgpl-3.0.txt

 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU LESSER GENERAL PUBLIC LICENSE version 3
			 https://www.gnu.org/licenses/lgpl-3.0.txt

END LICENSE AND COPYRIGHT
*/

/* * #@+
 * @author Marc Mittag
 * @package ZfExtended
 * @version 2.0
 *
 */

/*
 * Gibt Fehlerdetails nur für Fehler mit _errorCode größer 202 aus, da davon 
 * ausgegangen wird, dass alles andere nur Infomeldungen sind, bei denen nur die Message relevant ist
 */
?>
<h2><?php echo $this->exception->getMessage(); ?></h2>
<h3>Request URI:</h3>
<pre><?php echo htmlspecialchars($_SERVER['REQUEST_URI']); ?>
<h3>Stack trace:</h3>
<pre><?php echo $this->exception; ?>
</pre>
<h3>Request Parameters:</h3>
<pre><?php print_r($_REQUEST, true); ?>
</pre><?php 