<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of ZfExtended library
 
 Copyright (c) 2013 - 2017 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU LESSER GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file lgpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU LESSER GENERAL PUBLIC LICENSE version 3.0 requirements will be met:
https://www.gnu.org/licenses/lgpl-3.0.txt

 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU LESSER GENERAL PUBLIC LICENSE version 3
			 https://www.gnu.org/licenses/lgpl-3.0.txt

END LICENSE AND COPYRIGHT
*/

/**#@+
 * @author Marc Mittag
 * @package ZfExtended
 * @version 2.0
 *
 */

$config = Zend_Registry::get('config');
?>
  <h2><?php echo $this->translate->_('Anwendungsfehler'); ?></h2>
  <p><?php echo $this->translate->_('Wir bitten um Entschuldigung für die aufgetretene Störung!'); ?></p>
  <p><?php echo $this->translate->_('Unsere Administratoren werden automatisch benachrichtigt und werden sich umgehend mit Ihnen in Verbindung setzen.'); ?></p>
  <p><?php echo $this->translate->_('Sollte innerhalb des nächsten Arbeitstags keine Kontaktaufnahme erfolgt sein, liegt eine allgemeine Störung vor, die die automatische Benachrichtigung unserer Administratoren verhindert. Bitte benachrichtigen Sie uns dann möglichst umgehend unter den folgenden Kontaktdaten:'); ?></p>
  <p>
    <?php echo $config->runtimeOptions->contactData->emergencyContactDepartment; ?><br/>
    <?php echo $this->translate->_('Telefon:'); echo ' '.$config->runtimeOptions->contactData->emergencyTelephoneNumber; ?><br/>
    <?php echo $this->translate->_('E-Mail:'); echo ' '.$config->resources->mail->defaultFrom->email; ?><br/>
  </p>

  <?php 