<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of ZfExtended library

 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU LESSER GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file lgpl3-license.txt
 included in the packaging of this file.  Please review the following information
 to ensure the GNU LESSER GENERAL PUBLIC LICENSE version 3.0 requirements will be met:
https://www.gnu.org/licenses/lgpl-3.0.txt

 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU LESSER GENERAL PUBLIC LICENSE version 3
             https://www.gnu.org/licenses/lgpl-3.0.txt

END LICENSE AND COPYRIGHT
*/

/* @var $this Zend_View */
$config = Zend_Registry::get('config');
?>
  <h2><?php echo $this->translate->_('Application error'); ?></h2>
  <p><?php echo $this->translate->_('We apologize for the problem you encountered!'); ?></p>
  <p><?php echo $this->translate->_('Our administrators have been notified and will get in touch with you shortly.'); ?></p>
  <p><?php echo $this->translate->_('If no contact has been made within the next business day, a general malfunction is likely preventing the automatic notification of our administrators. In that case, please contact us as soon as possible using the following details:'); ?></p>
  <p>
    <?php echo $config->runtimeOptions->contactData->emergencyContactDepartment; ?><br/>
  </p>
<?php
if (! headers_sent() && getenv('T5_REDIRECT_ON_ERROR')) {
    echo '<p><b>You will be redirected automatically to our status page.</b></p>';
    header('Refresh: 5; url=' . getenv('T5_REDIRECT_ON_ERROR'));
}
