<?php
$config = Zend_Registry::get('config');
/* @var $config Zend_Config */
?>

<div id="header">
    <img src="<?php echo APPLICATION_RUNDIR; ?>/images/translate5.png?v=1" alt="<?php echo 'translate5'; ?>">
</div>
<h1><?= $this->translate->_('Wir sind <br/>bald wieder da!'); ?></h1>
<div style="clear:both;">
    <p>
<?= str_replace(
    '{appName}',
    $config->runtimeOptions->appName,
    $this->translate->_(
        'Wartungsarbeiten sind im Gange. <br/>{appName} wird nach Abschluss der Wartungsarbeiten wieder verf&#252;gbar sein.'
    )
);
?>
    </p>
    <p>
<?= str_replace(
    '{appName}',
    $config->runtimeOptions->appName,
    $this->translate->_('{appName} ist in wenigen Minuten wieder online!')
);
?>
    </p>
    <?php if (strlen($config->runtimeOptions->maintenance->message ?? '') > 0) { ?>
    <p style="font-weight: bold; font-style: italic;">
        <?php echo htmlspecialchars($config->runtimeOptions->maintenance->message ?? ''); ?>
    </p>
    <?php } ?>
    <p><?php echo htmlspecialchars($config->runtimeOptions->companyName); ?></p>
    <p id="last-reload" style="color:#cdcdcd;font-size:9px;"></p>
</div>
