<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of ZfExtended library
 
 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU LESSER GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file lgpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU LESSER GENERAL PUBLIC LICENSE version 3.0 requirements will be met:
https://www.gnu.org/licenses/lgpl-3.0.txt

 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU LESSER GENERAL PUBLIC LICENSE version 3
			 https://www.gnu.org/licenses/lgpl-3.0.txt

END LICENSE AND COPYRIGHT
*/

/**#@+
 * @author Marc Mittag
 * @package portal
 * @version 2.0
 *
 */
/**
 * Generiert das allgemeine Layout
 *
 * - Achtung: Bei Hinzufügen weiterer Layoutelemente darauf achten, dass diese
 *   im Viewhelper View_Helper_DisableBodyLayout deaktiviert werden
 */
$this->translate =  ZfExtended_Zendoverwrites_Translate::getInstance();

$config = Zend_Registry::get('config');
/* @var $config Zend_Config */

echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php echo $this->headTitle() ?>
        <?php   echo $this->headMeta() ?>
        <?php   echo $this->headLink() ?>
        <?php echo $this->headStyle() ?>
        <link rel="shortcut icon" href="<?php echo APPLICATION_RUNDIR.$config->runtimeOptions->server->pathToIMAGES; ?>/favicon.ico" type="image/x-icon"/>
        <?php echo $this->headScript() ?>
        <style>
		  body { text-align: center; padding: 150px; }
		  h1 { font-size: 50px; padding-top:10px;}
		  p { margin-bottom:10px; }
		  body { font: 20px Helvetica, sans-serif; color: #333; }
		  article { display: block; text-align: left; width: 650px; margin: 0 auto; }
          #header {float:left;margin-right:30px;}
		</style>
    </head>
    <body>
        
    <article>
        <?= $this->render('error/maintenance-content.phtml'); ?>
	</article>
<?php
if(!empty($_GET['testmaintenance'])) {
    echo '<!--';
}
?>
	<script>
        checkCount = 0;
        checkIntervalMs = 5000;
		checkMaintenance = function(){
		        var xhr = new XMLHttpRequest(),
                    d = new Date(),
		        	url = '<?php echo APPLICATION_RUNDIR;?>/login'; // browser will not cache HEAD requests
		        xhr.open('HEAD', url);
                checkCount++;
				xhr.onload = function() {
					if(xhr.status >= 200 && xhr.status < 400) {
    			        window.location.href = url;
					} else {
                        document.getElementById('last-reload').innerHTML = 'Last check started at: '+d.toLocaleString()+' (#'+checkCount+')';
                        setTimeout(checkMaintenance, checkIntervalMs);
                    }
		        };
		        xhr.send();
		};
        setTimeout(checkMaintenance, checkIntervalMs);
	</script>
<?php
if(!empty($_GET['testmaintenance'])) {
    echo '-->';
}
?>
  </body>
</html>
